### ISSUE TITLE
Phaser Official NPM Package

### ISSUE THREAD

**Issue by JoeDuncko** [JaapRood/phaser-unofficial#1]
Looks like there is an office NPM package for Phaser at https://www.npmjs.com/package/phaser now, so you can pull this down when you are ready.

**Comment by JaapRood** [comment]
That's awesome. At a quick first glance the problems with globals are fixed too, which is great.

I'll put a deprecation message on top here, redirecting people to the now official package. I won't pull it down from the registry though, as that would break anyone's Phaser who hasn't upgraded yet (including a project my own as well). Instead I'll official deprecate it through `npm deprecate`, giving anyone who installs it a warning as well.

**Comment by JoeDuncko** [comment]
Awesome! Sounds like a plan!
